### ISSUE TITLE
Required gems for Mac OS

### ISSUE THREAD

**Issue by maxAubain** [nezirz/ruby_webshot#1]
Hello,

I recently downloaded `ruby_webshot` to replace the now depreciated `webshot`, as you have described in the documentation.  I wanted to point out that to `require 'ruby_webshot'` without error on Mac OS, the installation of the [webdrivers gem](https://rubygems.org/gems/webdrivers/versions/4.2.0) is necessary.

Nice work!

**Comment by nezirz** [comment]
Hi @maxAubain  thank you very much for information.
